services:
  jobmanager:
    image: flink:1.19-java17
    ports:
      - 8381:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - flink

  taskmanager:
    image: flink:1.19-java17
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
    networks:
      - flink

networks:
  flink:
    external: true